### PR TITLE
Fixed `faster-simple-line-detector`

### PR DESCRIPTION
**Pull request by Wither362**

### CODE REVIEW

**Comment by Wither362** [comment]
IT WORKSSS!! @ShaharMS!! It compiles correctly!!

**Comment by ShaharMS** [comment]
Why is CI failing like that?

**Comment by ShaharMS** [comment]
Btw, the whole thing getUnsafePixel does is being a bit faster by not doing null/bound checking. OutsideBounds error usually means a getUnsafePixel call gone wrong.

**Comment by Wither362** [comment]
> 

Oh, thanks

**Comment by ShaharMS** [comment]
Also, why not just test yourself if you're getting the error? Testing on interp is the fastest thing to do for problems like this one

**Comment by Wither362** [comment]
> Also, why not just test yourself if you're getting the error? Testing on interp is the fastest thing to do for problems like this one

Because I’m at school :'(, and I’m using the tablet

**Comment by ShaharMS** [comment]
Oh wow, nice :D

**Comment by Wither362** [comment]
Sorry for the notifications, if you don’t want notifications from this pull request, click here:
notificati9n inage

**Comment by ShaharMS** [comment]
Nah it's fine, I think it's better seeing the progress. Feel free to ask me anything:)

**Comment by Wither362** [comment]
IT WORKS!

**Pull request closed without merging**
