### PR TITLE
Math problems… (Still in WIP)

### PR DESCRIPTION
**Pull request by Wither362**
## TODO:
- [ ] Simplify file.
- [ ] Add more functions (I can’t remember examples)
- [ ] Make the file functionality faster
- [ ] Add documentation

### CODE REVIEW

**Comment by ShaharMS** [comment]
About you editing the for loops, for loops don't include the last number anyways, so 0...width/height is valid

Just check the resulting images (test VisionMain on J's target and look at the image's on the webpage)

**Comment by ShaharMS** [comment]
Another thing, I've used floats instead of Point2D because performance is critical in these functions, and not using Point2D is faster & consumes less memory

**Comment by Wither362** [comment]
> Another thing, I've used floats instead of Point2D because performance is critical in these functions, and not using Point2D is faster & consumes less memory

Oh, thanks for that tip, if you want to edit something go ahead, I activated the checkbox for allowing you to edit my changes

**Comment by Wither362** [comment]
> About you editing the for loops, for loops don't include the last number anyways, so 0...width/height is valid

They don’t include the last number, but if I "quit" another Int, it will not look up for that pixel (I don’t know if it will work, I’m a little new with the pixels and the images code)

> Just check the resulting images (test VisionMain on J's target and look at the image's on the webpage)

Well, I can’t do that since I’m on iPad, not on computer…

**Pull request closed without merging**
