### PR TITLE
Rounded shapes (I might need help with it… WIP)

### PR DESCRIPTION
**Pull request by Wither362**
TODO:
- [ ] Prove that code works (I only tested it by using `trace`, I don’t know if it will work)
- [ ] Rounded Square
- [ ] Rounded Inverted Rectangle
- [ ] Adding more shapes…
- [ ] Functions for knowing if a coordinate exists inside the figure
<br>
It’s a cool feature I would like to be added, it uses an algorithm I’ve "created" because I don’t find information for doing it…
<br><br>
I created this pull request for you (Marcus) to see if this could be added, or if this code break everything, and I need help doing this…
<br><br>
So, @ShaharMS, if you can help me with this, it would help me a lot

### CODE REVIEW

**Comment by ShaharMS** [comment]
This looks interesting, I already need to redesign image views to work with arbitrary shapes & functions. This might need to wait though, since this stuff is performance critical (image views are taken into account each time you manipulate a pixel)

**Comment by Wither362** [comment]
> This looks interesting, I already need to redesign image views to work with arbitrary shapes & functions. This might need to wait though, since this stuff is performance critical (image views are taken into account each time you manipulate a pixel)

Ok, I know some ways to make the image stay in the right position, I could add them too (but only if you like the idea)

**Comment by ShaharMS** [comment]
Another thing, I think the approach of having more view stats (such as `rounded`) is probably preferred, since it makes the most sense with the current way of calculating views & probably includes the least overhead.

**Comment by Wither362** [comment]
> Another thing, I think the approach of having more view stats (such as `rounded`) is probably preferred, since it makes the most sense with the current way of calculating views & probably includes the least overhead.

Yeah, you’re right, but I can’t find a way to calculate a rounded rectangle, I asked my friends, and they told me this:
- You can see the coordinates of a rectangle with rounded corners by adding all the coordinates of the parent rectangle to a Vector or Array, and then removing the coordinates that don't match the rounded rectangle.
- The way to make a rectangle with round corners is quite easy, in the circle formula, we use the number PI, but if we increase the value of PI, it will shape us into a rectangle with round corners

**Comment by Wither362** [comment]
@ShaharMS, I have a question, how do I use these functions for this code to work:?
```hx
MathTools.radiansFromPointToPoint2D(start, end);
MathTools.radiansToSlope(radians);
MathTools.radiansToDegrees(radians);
```
I’ve seen them in Line2D.hx, and it may help with this

**Comment by ShaharMS** [comment]
The first function returns the angle between two points in radians, the second and third functions convert between different notations of angles - degrees, slopes and radians. You could see how I use these functions in other files

**Comment by Wither362** [comment]
Squircle? https://en.m.wikipedia.org/wiki/Squircle

**Pull request closed without merging**
